runtime: nodejs18

instance_class: F1 # Optional: Adjust the machine size as needed

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
  min_idle_instances: 1

handlers:
  - url: /.*
    script: auto
